### ISSUE TITLE
Field confirm_password

### ISSUE THREAD

**Issue by shubham9411** [Yathartha22/notices-api#1]
No need to check this field in the api we will check this in front end. 
Right now api is throwing an error for confirm password:
`{"confirm_password":["This field is required."]}`

**Comment by Yathartha22** [comment]
This is by default. Still I will have a look.

**Comment by Yathartha22** [comment]
Fixed this issue(sorry for no creating a PR 😁). But another problem is raised that `confirm_password` field is also returned in JSON as an empty string.
Will this create any problem? Otherwise, I will fix this tomorrow 😴.
