### ISSUE TITLE
Error: This field is required

### ISSUE THREAD

**Issue by shubham9411** [Yathartha22/notices-api#3]
If we leave any field blank it is sending an api response like this:
```
{
  "password": ["This field may not be blank."],
  "username": ["This field may not be blank."]
}
```
can it be changed to something like: 

```
{
  "password": ["Password field may not be blank."],
  "username": ["username field may not be blank."]
}
```
My question is, is it possible?

**Comment by Yathartha22** [comment]
Yes, it can be done, during login I have returned a message like you said, but don't know why it shows default message. I will look into it.

**Comment by Yathartha22** [comment]
I have fixed this issue, by mistake, I pushed commits in master branch rather than creating a PR(Sorry about it 😁).
Now if there is any error as such it is shown as:

```
{
    "status": false,
    "errors": [
        "email : This field may not be blank.",
        "password : This field may not be blank."
    ]
}
# a list of errors is created.
```
If this is ok for you, I will close the issue, otherwise suggest changes.
